/*
==============================================================================
CUSTOMER REPORT:
==============================================================================
*/

-- 1} Find the total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- 2} Find the total customers by countries
SELECT 
country,
COUNT(customer_id) AS total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- 3} Find total revenue is generated by each customer
SELECT
c.customer_key,
CONCAT (c.first_name, ' ', c.last_name) AS customer_name,
SUM(sales_amount) AS total_revenue
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
first_name,
last_name
ORDER BY total_revenue DESC;

 /* 
4} Group customers into three segmwnts based on their spending behaviour:
   - VIP: Customers with at least 12 months of history and spending more than 5,000.
   - Regular: Customers with at least 12 months of history but spending 5,000 or less.
   - New: Customers with a lifespan less than 12 months.
   And find the total number of customers by each group*/

WITH customer_spending AS (
SELECT 
c.customer_key,
SUM(f.sales_amount) AS total_spending,
MIN(order_date) AS first_order,
MAX(order_date) AS last_order,
DATEDIFF (MONTH, MIN(order_date), MAX(order_date)) AS lifespan
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key
)

SELECT
customer_segment,
COUNT(customer_key) AS total_customers
FROM (
SELECT
customer_key,
CASE WHEN lifespan >= 12 AND total_spending > 5000 THEN 'VIP'
WHEN lifespan >= 12 AND total_spending <= 5000 THEN 'Regular'
ELSE 'New'
END customer_segment
FROM customer_spending)t
GROUP BY customer_segment 
ORDER BY total_customers DESC;


/* 
-- 5} Highlights:
   a).Gathers essential fields such as names, ages, and transactional detils.
   b).Segments customers into cattegories (VIP, Regular, New) and age groups.
   c).Aggregates customer_level metrics:
     - total_orders
     - total sales
     - total quantity purchased
     - total products
     - lifespan (in months)
   d).Calcultes valuable KPIs:
     - renency (months since last order)
     - average order value
     - average monthly spend
*/

WITH base_query AS(
SELECT                --(Base Query: Retrieves core columns from tables)
f.order_number,
f.product_key,
f.order_date,
f.sales_amount,
f.quantity,
c.customer_key,
c.customer_number,
c.first_name,
c.last_name,
CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
DATEDIFF(year, c.birthdate, GETDATE()) age
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
WHERE order_date IS NOT NULL
)
, customer_aggregation AS (
--(Customer Aggregations: Summarize key metrics at the customer level)
SELECT 
customer_key,
customer_number,
customer_name,
age,
COUNT(DISTINCT order_number)  AS total_orders,
SUM(sales_amount) AS total_sales,
SUM(quantity) AS total_quantity,
COUNT(DISTINCT product_key) AS total_products,
MAX(order_date) AS last_order_date,
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan
FROM base_query
GROUP BY
customer_key,
customer_number,
customer_name,
age
)
SELECT
customer_key,
customer_number,
customer_name,
age,
CASE 
WHEN age < 20 THEN 'Under 20'
WHEN age BETWEEN 20 AND 29 THEN '20-29'
WHEN age BETWEEN 30 AND 39 THEN '30-39'
WHEN age BETWEEN 40 AND 49 THEN '40-49'
ELSE '50 and above'
END AS age_group,
CASE
WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'Regular'
ELSE 'New'
END AS customer_segment,
last_order_date,
DATEDIFF(month, last_order_date, GETDATE()) AS recency,
total_orders,
total_sales,
total_quantity,
total_products,
lifespan,
--(Compute average order value(AVO))
CASE WHEN total_sales = 0 THEN 0
ELSE total_sales / total_orders
END AS avg_order_value,
--(Compuate average monthly spend)
CASE WHEN lifespan = 0 THEN total_sales
ELSE total_sales / lifespan
END AS avg_monthly_spend
FROM customer_aggregation;

